projectmanager:
  imageVersion: 0.1.1  

global:
  postgresql:
    auth:
      postgresPassword: Is92n$8&z^EI
      username: aspnetuser
      password: Wh97G@3!pCeA
      database: aspnet-ProjectManager
  