apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-projectmanager  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-projectmanager
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-projectmanager
    spec:
      containers:
      - name: projectmanager       
        image: ghcr.io/jppgroup/projectmanager:{{ .Values.projectmanager.imageVersion }}
        args: ["run"]
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ConnectionStrings__DefaultConnection
          value: "Host={{ .Values.projectmanager.databaseaddress }};Database={{ .Values.global.postgresql.auth.database }};Username={{ .Values.global.postgresql.auth.username }};Password={{ .Values.global.postgresql.auth.password }}"
        - name: ASPNETCORE_PathBase
          value: "{{ .Values.projectmanager.prefix }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-projectmanager
spec:
  selector:
    app: {{ .Release.Name }}-projectmanager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
{{ if .Values.ingress.enable }}
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: {{ .Release.Name }}-projectmanager-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`{{ .Values.projectmanager.prefix }}/`)        
      services:
        - kind: Service
          name: {{ .Release.Name }}-projectmanager
          namespace: default
          port: 80
{{ end }}
{{ if .Values.gateway.enable }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-projectmanager-route
  namespace: default
spec:
  parentRefs:
  - name: main-gateway
    sectionName: httpin
    namespace: istio-system
  hostnames:
  - "services.cedarbarn.local"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ .Values.projectmanager.prefix }}
    backendRefs:
    - name: {{ .Release.Name }}-projectmanager
      port: 80
{{ end }}
          