apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-projectmanager  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-projectmanager
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-projectmanager
    spec:
      containers:
      - name: projectmanager       
        image: ghcr.io/jppgroup/projectmanager:{{ .Values.projectmanager.imageVersion }}
        args: ["run"]
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ConnectionStrings__DefaultConnection
          value: "Host={{ .Values.projectmanager.databaseaddress }};Database={{ .Values.global.postgresql.auth.database }};Username={{ .Values.global.postgresql.auth.username }};Password={{ .Values.global.postgresql.auth.password }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-projectmanager
spec:
  selector:
    app: {{ .Release.Name }}-projectmanager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: {{ .Release.Name }}-projectmanager-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/projectmanager/`)  
      middlewares:                    
      - name: {{ .Release.Name }}-projectmanager-ingress-prefixstrip   
      services:
        - kind: Service
          name: projectmanager
          namespace: default
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-projectmanager-ingress-prefixstrip 
spec:
  stripPrefix:
    prefixes:
      - /projectmanager/   
          